name: publish
on: [push]
jobs:
publish-demo:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Create Docker Image
run: |
       docker build . --tag ghcr.io/cphebo/demo:latest
       docker run ghcr.io/cphebo/demo:latest
       docker push ghcr.io/cphebo/demo:latest